# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
name: UI CI

on:
  push:
    branches:
      - master
      - release-*

  # Run build for any PR
  pull_request:
    paths:
      - "ui/**"
      - ".github/workflows/gh-pages.yml"

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ui

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:  
          sparse-checkout: |
            ui/
            .github/
      
      - name: Spy
        run: ls -la; pwd

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "ui/package-lock.json"
        
      - name: Install dependencies from package-lock
        run: npm ci

      - name: Build UI with node
        run: npm run build --if-present

#     no tests yet!
#     - name: Run tests
#     - run: npm test
